"""
http://projecteuler.net/index.php?section=problems&id=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def solve():
    total = 0
    nth_term, mth_term = 1, 2
    while nth_term < 4000000:
        if nth_term % 2 == 0:
            total += nth_term
        nth_term, mth_term = mth_term, nth_term + mth_term
    print(total)

if __name__ == '__main__':
    solve()